in_file_paths:
  - /eos/home-s/shudong/workspace/HHML/Run3/HHMLAnalysisCode/output/ntuple/merged/CAF_ntuples/job_0423_2lSC/2lSC_hhml_ana_ggF_kl1_PhPy8EG.root
  - /eos/home-s/shudong/workspace/HHML/Run3/HHMLAnalysisCode/output/ntuple/merged/CAF_ntuples/job_0423_2lSC/2lSC_hhml_ana_VBF_kl1k2v1kv1_MGPy8EG.root
  - /eos/home-s/shudong/workspace/HHML/Run3/HHMLAnalysisCode/output/ntuple/merged/CAF_ntuples/job_0423_2lSC/2lSC_singleH.root
  - /eos/home-s/shudong/workspace/HHML/Run3/HHMLAnalysisCode/output/ntuple/merged/CAF_ntuples/job_0423_2lSC/2lSC_top.root
  - /eos/home-s/shudong/workspace/HHML/Run3/HHMLAnalysisCode/output/ntuple/merged/CAF_ntuples/job_0423_2lSC/2lSC_Vjets.root
  - /eos/home-s/shudong/workspace/HHML/Run3/HHMLAnalysisCode/output/ntuple/merged/CAF_ntuples/job_0423_2lSC/2lSC_VV.root
  - /eos/home-s/shudong/workspace/HHML/Run3/HHMLAnalysisCode/output/ntuple/merged/CAF_ntuples/job_0423_2lSC/2lSC_VVV.root
  - /eos/home-s/shudong/workspace/HHML/Run3/HHMLAnalysisCode/output/ntuple/merged/CAF_ntuples/job_0423_2lSC/2lSC_Vy.root

in_tree_name: sr
merge_input: false

output_dir: local_test/output
out_tree_name: sr
k_folds: 3
fold_splitting_var: eventNumber

new_variables:
  label_signal: "np.isin(dsid, [600862, 600853, 600854, 600855, 600856, 600857, 600858])"
  label_background: "~np.isin(dsid, [600862, 600853, 600854, 600855, 600856, 600857, 600858])"
  valid: "pt > 0"

object_names:
  - l1
  - l2
  - j1
  - j2
  - met

object_variables:
  - pt
  - eta
  - phi
  - e
  - pdg
  - charge

event_variables:
  - HT_vis
  - HT_lep
  - HT_jet
  - HT_lepMET
  - m_all
  - dilep_type
  - xgb_score
  - eventNumber
  - dsid
  - weight
  - truth_HH_m

