model: models.ParticleTransformer.ParticleTransformer

model_params:
  input_dim: 6
  num_classes: 2
  pair_input_dim: 4
  use_pre_activation_pair: false
  embed_dims: [64, 256, 64]
  pair_embed_dims: [32, 32, 32]
  num_heads: 4
  num_layers: 4
  num_cls_layers: 1
  block_params: null
  cls_block_params:
    'dropout': 0
    'attn_dropout': 0
    'activation_dropout': 0
  fc_params: []
  activation: 'gelu'
  trim: True
  for_inference: False

load_model:

training_step_function:

validation_step_function:

test_step_function:

loss_function:
  name: loss_functions.loss.CrossEntropyLossWeighted
  params:

start_lr: 0.001

optimizer: "Ranger"
#  name: AdamW
#  params:

lr_scheduler: "steps"
#  name: steps
#  params:

metrics:
  Accuracy:
    function: core.metrics.weighted_accuracy
    stages: ['train', 'val', 'test']
    is_reference: True
    on_step: true
    on_epoch: true
  AUC:
    function: core.metrics.weighted_auc_2cls
    stages: ['val', 'test']
    on_step: false
    on_epoch: true
  CM:
    function: core.metrics.weighted_confusion_matrix_2cls
    stages: ['val', 'test']
    on_step: false
    on_epoch: true


