model: synapse.models.ParticleTransformer.ParticleTransformerGlobalFeat

model_params:
  input_dim: 6
  global_input_dim: 6
  num_classes: 2
  pair_input_dim: 4
  use_pre_activation_pair: false
  embed_dims: [32, 128, 32]
  global_embed_dims: [32, 128, 32]
  pair_embed_dims: [16, 16, 16]
  num_heads: 2
  num_layers: 2
  num_cls_layers: 1
  block_params: null
  cls_block_params:
    'dropout': 0
    'attn_dropout': 0
    'activation_dropout': 0
  fc_params: 
    - [32,0]
    - [128,0]
    - [32,0]
  activation: 'gelu'
  trim: True
  for_inference: False

load_model:

training_step_function:

validation_step_function:

test_step_function:

loss_function:
  name: synapse.loss_functions.loss.CrossEntropyLossWeighted
  params:

start_lr: 0.001

optimizer: "Ranger"
#  name: AdamW
#  params:

lr_scheduler: "steps"
#  name: steps
#  params:

metrics:
  Accuracy:
    function: synapse.core.metrics.weighted_accuracy
    stages: ['train', 'val', 'test']
    is_reference: True
    on_step: true
    on_epoch: true
  AUC:
    function: synapse.core.metrics.weighted_auc
    stages: ['val', 'test']
    on_step: false
    on_epoch: true
  CM:
    function: synapse.core.metrics.weighted_confusion_matrix
    stages: ['val', 'test']
    on_step: false
    on_epoch: true


