run_dir: 'local_test/run_1'  # Directory to save the run outputs

run_mode: ['train', 'test']

device: 'gpu' # 'cpu' or 'gpu'

n_devices: 'auto'  # 'auto' for automatic detection, or specify a number

epochs: 3

start_epoch: 0

batch_size: 1024

num_workers: 5

val_sanity_check: false  # Set to true to run a 2 batch sanity check on validation data

cross_validation: true

cross_validation_var: 'eventNumber'  # Variable to use for cross-validation, must be in the 'assistants' in data config

k_folds: 3

logger_config:
  enable_stdout: true
  log_file: 'logs/run_log_{auto}.log'

seed: 42
use_amp: false

test_output: 'test_output/output_{auto}.root'  # Path to save test output file

#onnx_path: 'onnx_model/model_{auto}.onnx'  # Path to save ONNX model file after test

# export_onnx: 'model.onnx' # not supported yet